### ISSUE TITLE
how i do make it work i use tampermonkey but it's not working or i missed something :skull:

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [ciulinuwu/ciulin-s-youtube#1]

**Comment by asfasdfasdfsdsdf** [comment]
so bruh i need make it work :Skull:

**Comment by ciulinuwu** [comment]
Hey! What does it show on the Main Page?

**Comment by asfasdfasdfsdsdf** [comment]
i use firefox

**Comment by asfasdfasdfsdsdf** [comment]
i can do it to show it

**Comment by asfasdfasdfsdsdf** [comment]
here is:
LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable. desktop_polymer.js:4733:9
Some cookies incorrectly use the recommended "SameSite" attribute 16
Request from foreign origin blocked: The single origin policy prevents reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request failed). Status code: (null).

Loading <script> at 'https://static.doubleclick.net/instream/ad_status.js' failed. www.youtube.com:1:1
TypeError: base is null www.youtube.com:606:14
Code map error: Error: request failed with status 404
Resource URL: https://www.youtube.com/
Code map URL: global_styles_sass.css.map

The MouseEvent.mozPressure property is deprecated. Use PointerEvent.pressure to replace it. desktop_polymer.js:1506:45
Will-change consumes too much memory. The budget limit is the document surface area multiplied by 3 (1483200 pixels). Will-change entries that exceed the budget will be ignored. www.youtube.com
This page is loaded in Quirks mode. This may affect the layout of the page. For Standards mode, use "<!DOCTYPE html>".
3 blank.html
The resource "https://i.ytimg.com/generate_204", already downloaded from the preload link, has not been used for several seconds. Make sure all attributes of the "preload" tag have been set correctly. www.youtube.com

**Comment by asfasdfasdfsdsdf** [comment]
:skull:

**Comment by ciulinuwu** [comment]
Hmm.. Okay, what does it show on the Main Page? Is it still the same YouTube, a white screen, or part of the script loaded?

**Comment by asfasdfasdfsdsdf** [comment]
just normal page

**Comment by asfasdfasdfsdsdf** [comment]
it didn't load and showing the normal youtube

**Comment by asfasdfasdfsdsdf** [comment]
oh gonna try

**Comment by asfasdfasdfsdsdf** [comment]
but i cleared cookies already

**Comment by ciulinuwu** [comment]
No consent screen?

**Comment by asfasdfasdfsdsdf** [comment]
yes it not showing and it only shows normal youtube

**Comment by ciulinuwu** [comment]
Okay I'm gonna add some code that'll output debugging stuff to the Console. Let me know what it says.

**Comment by asfasdfasdfsdsdf** [comment]
ok

**Comment by asfasdfasdfsdsdf** [comment]
it showed this:

Some cookies incorrectly use the recommended "SameSite" attribute 11
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://rr5---sn-gvnuxaxjvh-nufl.googlevideo.com/videoplayback?expire=1654542407&ei=5_udYvW4MYmD7QTMpYuoAQ&ip=46.63.209.190&id=o -AGYNI1TMBwCeQChn3O3dvXs0VzOmP3QDc8HHxu5aZoLT&itag=398&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=jl&mm =31%2C29&mn=sn-gvnuxaxjvh-nufl%2Csn-n8v7znlk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=802500&spc=4ocVC6lR67RJSzS_9kSw5xdMRM5KNxNSLtqxnCtjkaWX&vprv=1&mime=video%2Fmp4&ns=SUTkNzAgmxtqjEwMZIQy6XkG&gir=yes&clen=436642314&dur=1360.266&lmt=1617083184946257&mt=1654520462&fvip=3&keepalive= yes&fexp=24001373%2C24007246&c=WEB&txp=5436432&n=cKkjzi_uz3gVXw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgGItzW9kRX1LrICJbEzVCmCcuxWgrYzHAP20M8gBmJE0CIGLoAC0paba-lFd0Qik51yDsr3BbT1Yfi 71ouOKnS_wl&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIga5YpfZ7Pot5dL0hEze-_51pYjbLbCfi556pHZVO0Y9QCIEn68LcZJrMveoOUQ-LAbbbnVOb0SGPu8dzmClj1oej4&alr=yes&cpn=i6Xw1Q1J556e47-S&cver=2.20220602.00.00&range=0-1150066&rn=1&rbuf=0&altitags=397%2C396 base.js: 4430:117
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://rr5---sn-gvnuxaxjvh-nufl.googlevideo.com/videoplayback?expire=1654542407&ei=5_udYvW4MYmD7QTMpYuoAQ&ip=46.63.209.190&id=o -AGYNI1TMBwCeQChn3O3dvXs0VzOmP3QDc8HHxu5aZoLT&itag=251&source=youtube&requiressl=yes&mh=jl&mm=31%2C29&mn=sn-gvnuxaxjvh-nufl%2Csn-n8v7znlk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=802500&spc=4ocVC6lR67RJSzS_9kSw5xdMRM5KNxNSLtqxnCtjkaWX&vprv=1&mime=audio%2Fwebm&ns=SUTkNzAgmxtqjEwMZIQy6XkG&gir=yes&clen=19993610&dur =1360.381&lmt=1603076070490011&mt=1654520462&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=cKkjzi_uz3gVXw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur% 2Clmt&sig=AOq0QJ8wRQIhAJPwCCtzQgLA5Jqdfw4xC4ucO2Hq2YrNVaGZq3L5sfGsAiAVoJ92vsLASP0UUsj7WE6zDzOCmG0Orfq-mBP5boqFdA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIga5YpfZ7Pot5dL0hEze-_51pYjbLbCfi55 6pHZVO0Y9QCIEn68LcZJrMveoOUQ-LAbbbnVOb0SGPu8dzmClj1oej4&alr=yes&cpn=i6Xw1Q1J556e47-S&cver=2.20220602.00.00&range=0-68144&rn=2&rbuf=0 base.js:4430:117
Autoplay is allowed only if the user confirms that the user is actively on the site or the sound is turned off in the video. base.js:8280:33
LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable. desktop_polymer.js:4733:9
Referrer policy: The less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://www.gstatic.com/youtube/img/emojis/emojis-svg-9.json desktop_polymer.js:1124:426
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://googleads.g.doubleclick.net/pagead/id desktop_polymer.js:1124:426
[Ciulin's YouTube] Starting script... Ciulin's YouTube.user.js:34:24
[Ciulin's YouTube] YouTube Type: Not an embed Ciulin's YouTube.user.js:34:24
[Ciulin's YouTube] Cookie Check: Searching for CONSENT Ciulin's YouTube.user.js:34:24
[Ciulin's YouTube] Cookie Check: CONSENT does not exist. Ciulin's YouTube.user.js:34:24
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://i.ytimg.com/vi_webp/457ufZmfeuY/maxresdefault.webp maxresdefault.webp
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://i.ytimg.com/vi/0l7A5XckeRM/maxresdefault.jpg base.js:9014:478
Referrer policy: Less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://i.ytimg.com/vi_webp/cH0u1visfyo/maxresdefault.webp base.js:9014:478
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://i.ytimg.com/vi_webp/pzxyHvpBKxs/maxresdefault.webp base.js:9014:478
Referrer policy: Less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://i.ytimg.com/vi_webp/hYLz0ggNIio/maxresdefault.webp base.js:9014:478
Referrer policy: Less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://i.ytimg.com/an/V6JVu_u9vxvkd5gjJ5bkzA/featured_channel.jpg?v=5c50cef9 base.js:3151:331
Referrer policy: The less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create base.js:6362: 76
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://static.doubleclick.net/instream/ad_status.js spf.js:36:469
Load <script> at address 
"https://static.doubleclick.net/instream/ad_status.js" failed. watch:1:1
Autoplay is allowed only if the user confirms that the user is actively on the site or the sound is turned off in the video. base.js:8280:33
The MouseEvent.mozPressure property is deprecated. Use PointerEvent.pressure to replace it. base.js:1683:347
Referrer policy: Менее строгая политика origin-when-cross-origin игнорирована для междоменного запроса: https://www.google.com/pagead/lvz?evtid=AKB78cgWAyOi01gW5ix1bmw15EZKaXDk4CMUuGtD_hQF7QeGBfpQxngocms9zvA0KmsbAJ1hrF5Ze8mGCsO_LAWBj08YTugELg&req_ts=1654520808&pg=MainAppBootstrap%3AWatch&az=1&sigh=AKFpyYWkja7BsBMKNk3HU1J0a4uCUJMFEw desktop_polymer.js:1410
Referrer policy: Менее строгая политика origin-when-cross-origin игнорирована для междоменного запроса: https://www.google.ru/pagead/lvz?evtid=AKB78cgWAyOi01gW5ix1bmw15EZKaXDk4CMUuGtD_hQF7QeGBfpQxngocms9zvA0KmsbAJ1hrF5Ze8mGCsO_LAWBj08YTugELg&req_ts=1654520808&pg=MainAppBootstrap%3AWatch&az=1&sigh=AKFpyYWkja7BsBMKNk3HU1J0a4uCUJMFEw desktop_polymer.js:1410
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://rr5---sn-gvnuxaxjvh-nufl.googlevideo.com/videoplayback?expire=1654542407&ei=5_udYvW4MYmD7QTMpYuoAQ&ip=46.63.209.190&id=o -AGYNI1TMBwCeQChn3O3dvXs0VzOmP3QDc8HHxu5aZoLT&itag=251&source=youtube&requiressl=yes&mh=jl&mm=31%2C29&mn=sn-gvnuxaxjvh-nufl%2Csn-n8v7znlk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=802500&spc=4ocVC6lR67RJSzS_9kSw5xdMRM5KNxNSLtqxnCtjkaWX&vprv=1&mime=audio%2Fwebm&ns=SUTkNzAgmxtqjEwMZIQy6XkG&gir=yes&clen=19993610&dur =1360.381&lmt=1603076070490011&mt=1654520462&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=cKkjzi_uz3gVXw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur% 2Clmt&sig=AOq0QJ8wRQIhAJPwCCtzQgLA5Jqdfw4xC4ucO2Hq2YrNVaGZq3L5sfGsAiAVoJ92vsLASP0UUsj7WE6zDzOCmG0Orfq-mBP5boqFdA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIga5YpfZ7Pot5dL0hEze-_51pYjbLbCfi55 6pHZVO0Y9QCIEn68LcZJrMveoOUQ-LAbbbnVOb0SGPu8dzmClj1oej4&alr=yes&cpn=i6Xw1Q1J556e47-S&cver=2.20220602.00.00&range=68145-154728&rn=3&rbuf=4309 base.js3
TypeError: base is null watch:606:14
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://yt3.ggpht.com/ytc/AKedOLSjWtxYToVXhIt9x0U2T2YqGtlt6z0IITPK3Nr_=s48-c-k-c0x00ffffff-no-rj desktop_polymer.js:9024:72
Referrer policy: The less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://yt3.ggpht.com/ipz5Awa11JqJpadABHIXR0-GiBpvgFUm5ZUFm19BRAwWcjMzQGo22oCYRTaF-IDhaFjVlBLLzg=s100-w72-h100-c-ndr-ff-ff-polymer_ff desktop .js:9024:72
Referrer policy: Less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://yt3.ggpht.com/-uI-rr20i-uc/AAAAAAAAAAAI/AAAAAAAAAAA/lh8vSbbhYrc/s136-w136-h136-nd-rj /photo.jpg desktop_polymer.js:9024:72
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://rr5---sn-gvnuxaxjvh-nufl.googlevideo.com/videoplayback?expire=1654542407&ei=5_udYvW4MYmD7QTMpYuoAQ&ip=46.63.209.190&id=o -AGYNI1TMBwCeQChn3O3dvXs0VzOmP3QDc8HHxu5aZoLT&itag=251&source=youtube&requiressl=yes&mh=jl&mm=31%2C29&mn=sn-gvnuxaxjvh-nufl%2Csn-n8v7znlk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=802500&spc=4ocVC6lR67RJSzS_9kSw5xdMRM5KNxNSLtqxnCtjkaWX&vprv=1&mime=audio%2Fwebm&ns=SUTkNzAgmxtqjEwMZIQy6XkG&gir=yes&clen=19993610&dur =1360.381&lmt=1603076070490011&mt=1654520462&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5431432&n=cKkjzi_uz3gVXw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur% 2Clmt&sig=AOq0QJ8wRQIhAJPwCCtzQgLA5Jqdfw4xC4ucO2Hq2YrNVaGZq3L5sfGsAiAVoJ92vsLASP0UUsj7WE6zDzOCmG0Orfq-mBP5boqFdA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIga5YpfZ7Pot5dL0hEze-_51pYjbLbCfi55 6pHZVO0Y9QCIEn68LcZJrMveoOUQ-LAbbbnVOb0SGPu8dzmClj1oej4&alr=yes&cpn=i6Xw1Q1J556e47-S&cver=2.20220602.00.00&range=154729-301402&rn=4&rbuf=10001 base30:14
Referrer policy: The less restrictive origin-when-cross-origin policy is ignored for cross-domain request: https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/GenerateIT base.js:6362: 76
Referrer policy: Less restrictive origin-when-cross-origin policy ignored for cross-domain request: https://rr5---sn-gvnuxaxjvh-nufl.googlevideo.com/videoplayback?expire=1654542407&ei=5_udYvW4MYmD7QTMpYuoAQ&ip=46.63.209.190&id=o -AGYNI1TMBwCeQChn3O3dvXs0VzOmP3QDc8HHxu5aZoLT&itag=397&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=jl&mm =31%2C29&mn=sn-gvnuxaxjvh-nufl%2Csn-n8v7znlk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=802500&spc=4ocVC6lR67RJSzS_9kSw5xdMRM5KNxNSLtqxnCtjkaWX&vprv=1&mime=video%2Fmp4&ns=SUTkNzAgmxtqjEwMZIQy6XkG&gi

**Comment by asfasdfasdfsdsdf** [comment]
and it's not working still

**Comment by asfasdfasdfsdsdf** [comment]
:skull:

**Comment by asfasdfasdfsdsdf** [comment]
bruh ok

**Comment by asfasdfasdfsdsdf** [comment]
Lmao

**Comment by ciulinuwu** [comment]
WAIT I MADE A FUCK UP

**Comment by ciulinuwu** [comment]
Okay there. I hope it works now

**Comment by asfasdfasdfsdsdf** [comment]
worked but didn't show 2012 youtube and here's is what debug showed:
LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable. desktop_polymer.js:4733:9
Some cookies incorrectly use the recommended "SameSite" attribute 24
Automatically granted storage access for First-Party Isolation "https://accounts.google.com" to "https://www.youtube.com". www.youtube.com
[Ciulin's YouTube] Starting script... Ciulin's YouTube.user.js:34:24
[Ciulin's YouTube] YouTube Type: Not an embed Ciulin's YouTube.user.js:34:24
[Ciulin's YouTube] Cookie Check: Searching for CONSENT Ciulin's YouTube.user.js:34:24
[Ciulin's YouTube] Cookie Check: CONSENT does not exist. Ciulin's YouTube.user.js:34:24
Will-change consumes too much memory. The budget limit is the document surface area multiplied by 3 (1779840 pixels). Will-change entries that exceed the budget will be ignored. www.youtube.com
Loading <script> at 'https://static.doubleclick.net/instream/ad_status.js' failed. www.youtube.com:1:1
TypeError: base is null www.youtube.com:606:14
The MouseEvent.mozPressure property is deprecated. Use PointerEvent.pressure to replace it. desktop_polymer.js:1506:45
Code map error: Error: request failed with status 404
Resource URL: https://www.youtube.com/
Code map URL: global_styles_sass.css.map

The resource "https://i.ytimg.com/generate_204", already downloaded from the preload link, has not been used for several seconds. Make sure all attributes of the "preload" tag have been set correctly.

**Comment by ciulinuwu** [comment]
*internal screaming*

**Comment by ciulinuwu** [comment]
Did you grab the debug3 version? I forgot to move the bypasser on top of the rest on debug2 XD

**Comment by asfasdfasdfsdsdf** [comment]
It worked now

**Comment by asfasdfasdfsdsdf** [comment]
one i hate when i use this script logged it like looks like loged out (side bar i meaning)

**Comment by ciulinuwu** [comment]
Oh, it doesn't show the username?

**Comment by asfasdfasdfsdsdf** [comment]
and history page

**Comment by asfasdfasdfsdsdf** [comment]
btw, there's should normal side bar when logged in

**Comment by ciulinuwu** [comment]
Yeah. I'll add them in when possible!

**Comment by asfasdfasdfsdsdf** [comment]
XD thanks
