### ISSUE TITLE
Video progress bar on channel home page goes offscreen when scrubbing

### ISSUE THREAD

**Issue by THErlego** [ciulinuwu/ciulin-s-youtube#17]
![image](https://user-images.githubusercontent.com/104604446/177899097-ca832882-9c87-4377-bb06-0539b6db1d09.png)

**Comment by ciulinuwu** [comment]
Hi! I'm already aware of this bug and I don't know how to fix this yet. I'll keep you updated here if I manage to fix it!

**Comment by ciulinuwu** [comment]
Hello again. I lied, I've pushed a fix out bade43d0a77109e03d137f709779557e66e9bf2e xD
