### ISSUE TITLE
In player menu it's new

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [ciulinuwu/ciulin-s-youtube#18]
new player menu is huge

**Comment by asfasdfasdfsdsdf** [comment]
NVM

**Comment by asfasdfasdfsdsdf** [comment]
fuck it started again

**Comment by ciulinuwu** [comment]
Hey! Can you explain how it's huge?

**Comment by asfasdfasdfsdsdf** [comment]
when i press on player by right button it opens new menu not old and also huge

**Comment by ciulinuwu** [comment]
Alright. I'll work on it.
