### ISSUE TITLE
channel page does not appear

### ISSUE THREAD

**Issue by asfasdfasdfsdsdf** [ciulinuwu/ciulin-s-youtube#19]
fuck it don't appear

**Comment by pixdoet** [comment]
It appears that you're posting from a mobile phone. Please be aware that no mobile phone posting is allowed on GitHub and please refrain from posting from a mobile phone again or disciplinary action will be taken which might results in account termination and law enforcement. Thank you for your attention and have a nice day.

**Comment by asfasdfasdfsdsdf** [comment]
i'm on pc
not phone

**Comment by ciulinuwu** [comment]
What's the URL @asfasdfasdfsdsdf?

**Comment by asfasdfasdfsdsdf** [comment]
youtube.com

**Comment by ciulinuwu** [comment]
I mean, what's the full URL of the channel page.

**Comment by asfasdfasdfsdsdf** [comment]
channel/UCrv1Mn7zUzzeJjOFdiMezSQ
