### ISSUE TITLE
No comments

### ISSUE THREAD

**Issue by coffeemccoffee** [ciulinuwu/ciulin-s-youtube#20]
There's basically no comment section in videos with this script on.
![image](https://user-images.githubusercontent.com/104205144/178019719-fb5b49c9-58c8-44fc-962e-9da1f31cf017.png)

**Comment by ciulinuwu** [comment]
Hi. I haven't implemented comments yet. The script is still super WIP.

**Comment by ciulinuwu** [comment]
Hi. I have released 0.5.24. You cannot leave comments yet, but you can view them now. I will finish them later.
