### ISSUE TITLE
Blank screen shown on Chrome

### ISSUE THREAD

**Issue by sydia1103** [ciulinuwu/ciulin-s-youtube#21]
On Chrome 86.0.4240.75, with the latest version of TamperMonkey, sometimes the latest version of your script fails to display properly on the homepage, although the watch page works. I tested in Firefox and it works. No errors in console just a blank page after trying to load.

**Comment by ciulinuwu** [comment]
Hi. Dang update your Chrome!! Can you show me some screenshots of the disoriented homepage? And are you signed in on YouTube?

**Comment by sydia1103** [comment]
![Screen Shot 2022-07-08 at 5 59 10 PM](https://user-images.githubusercontent.com/69560065/178079986-48f126e1-9d21-443a-b37a-4244118e9587.png)
All it shows is this blank screen here. Yes, I am logged in.

**Comment by ciulinuwu** [comment]
I'll look into it

**Comment by ciulinuwu** [comment]
Closed due to incompatibility with Chromium. Please use Mozilla Firefox to use the script.

**Comment by ciulinuwu** [comment]
Hey! Can you try the script on Chrome? I changed the document-start thing to document-load instead and I don't know if that fixes it!

**Comment by sydia1103** [comment]
Hi, which branch is this in? I don't see any updates in the master branch.

**Comment by ciulinuwu** [comment]
Use the branch from earlier! ^^ I'm waiting with pushing stuff to Master until I've fixed all major issues!

**Comment by ciulinuwu** [comment]
Hi. Can you please let me know if your problem is solved. I'll close this in 2 days because I need to be sure it's an issue that affects others as I can't replicate this.

**Comment by sydia1103** [comment]
Doesn't seem to work still even with the latest 0.5.25. No errors in console, it loads polymer first and then tries to load your script, but it fails and shows a blank screen.

**Comment by ciulinuwu** [comment]
Can you please send me a screenshot of the Console.

**Comment by ciulinuwu** [comment]
OH. LOL. I didn't see you said there weren't any errors in the console. Sorry! Just to be sure does it only occur on the homepage and not /watch, (/channel, /c & /user), /feed/explore and /results?

**Comment by ciulinuwu** [comment]
Closed due to inactivity.

**Comment by sydia1103** [comment]
@ciulinuwu It seems with the latest update, the script works on the homepage, results, and feed/explore but not on channels, or videos, but the videos seem to play in the background.

**Comment by ciulinuwu** [comment]
Hi @sydia1103. Can you please open a new bug report and use the format stated on the project's main page. Remember to include screenshots of the Console output from the channel and video page. Thank you.
