### ISSUE TITLE
When logged in new layout appears

### ISSUE THREAD

**Issue by PANMARSAG14** [ciulinuwu/ciulin-s-youtube#23]
Hello, i appreciate your work on the script, but there is one bug. When logged in, for some reason, the new layout appears.
![firefox_6tSsiZ3F5k](https://user-images.githubusercontent.com/81510862/178140724-c3d69672-34ce-4596-ad9e-cb15e105a9f3.png)

**Comment by ciulinuwu** [comment]
Argh. Can you please open up DevTools and send me a screenshot of the error coming from the script?

**Comment by PANMARSAG14** [comment]
LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable. [desktop_polymer.js:5867:9](https://www.youtube.com/s/desktop/83093386/jsbin/desktop_polymer.vflset/desktop_polymer.js)
Uncaught (in promise) TypeError: isLoggedIn.actions[0].openPopupAction.popup.multiPageMenuRenderer.sections[0].multiPageMenuSectionRenderer.items[0].compactLinkRenderer.navigationEndpoint is undefined
    checkLogin moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:2271
    buildYouTube moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:2305
    async*tms_720259d3_a972_4206_a6a2_a7d55206438d$/</< moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:3326
    async*tms_720259d3_a972_4206_a6a2_a7d55206438d$/< moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:3335
    tms_720259d3_a972_4206_a6a2_a7d55206438d$ moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:3336
    it https://www.youtube.com/:14
    window["__p__12109575.602090336"]/</< moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:1
    window["__p__12109575.602090336"]/< moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:1
    "__p__12109575.602090336" moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:3337
    it https://www.youtube.com/:14
    set https://www.youtube.com/:3
    <anonymous> moz-extension://0b2495b7-a59b-45f0-abfd-3193e2bd5600/userscripts/Ciulin's YouTube.user.js?id=720259d3-a972-4206-a6a2-a7d55206438d:1
    it https://www.youtube.com/:14
    t https://www.youtube.com/:4
    it https://www.youtube.com/:14
    y https://www.youtube.com/:6
    send https://www.youtube.com/:7
    V https://www.youtube.com/:3
    E_u https://www.youtube.com/:4
    E_u https://www.youtube.com/:4
    create eval:64
    create eval:65
    l eval:6
    n eval:5
    run eval:6
    TM_back eval:67
line 14 > eval:2271:17
Cookie “SOCS” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [lvz](https://www.google.com/pagead/lvz?evtid=ADKXDuZ-jw01bZNNm76vNY58FgpqTjYYGwxqeGDXM30lzGLy-a9B93qPDKW_krQqdX7952o0vgmd8Pw1aPtDhY-QeQv43B8ujA&req_ts=1657449150&pg=MainAppBootstrap%3AHome&az=1&sigh=AN1MEdNWuDfUTE1SiB64d3ih_WqHrV5myg)
Cookie “AEC” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [lvz](https://www.google.com/pagead/lvz?evtid=ADKXDuZ-jw01bZNNm76vNY58FgpqTjYYGwxqeGDXM30lzGLy-a9B93qPDKW_krQqdX7952o0vgmd8Pw1aPtDhY-QeQv43B8ujA&req_ts=1657449150&pg=MainAppBootstrap%3AHome&az=1&sigh=AN1MEdNWuDfUTE1SiB64d3ih_WqHrV5myg)
Błąd mapy źródła: Error: request failed with status 404
URL zasobu: https://www.youtube.com/
URL mapy źródła: yt-swatch-behavior_custom_style.css.map

Użycie pamięci przez własność „will-change” jest zbyt wysokie. Limit budżetu jest powierzchnią dokumentu pomnożoną przez 3 (1143135 px). Wystąpienia „will-change” ponad budżet będą ignorowane. [www.youtube.com](https://www.youtube.com/)
Metoda „MouseEvent.mozPressure” jest przestarzała. Zamiast niej należy korzystać z „PointerEvent.pressure”. [desktop_polymer.js:1596:45](https://www.youtube.com/s/desktop/83093386/jsbin/desktop_polymer.vflset/desktop_polymer.js)
Cookie “SOCS” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [VvLlBeM63Uw2J1UyqqhsQRbvWBCU03kO1hra0OcUR60.js](https://www.google.com/js/th/VvLlBeM63Uw2J1UyqqhsQRbvWBCU03kO1hra0OcUR60.js)
Cookie “AEC” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [VvLlBeM63Uw2J1UyqqhsQRbvWBCU03kO1hra0OcUR60.js](https://www.google.com/js/th/VvLlBeM63Uw2J1UyqqhsQRbvWBCU03kO1hra0OcUR60.js)
Zasób w „https://i.ytimg.com/generate_204” wstępnie wczytany ze wstępnym wczytywaniem odnośnika nie został użyty w ciągu kilku sekund. Upewnij się, że wszystkie atrybuty znacznika wstępnego wczytywania są poprawnie ustawione. [www.youtube.com](https://www.youtube.com/)
Błąd mapy źródła: Error: request failed with status 404
URL zasobu: https://www.youtube.com/s/desktop/83093386/jsbin/custom-elements-es5-adapter.vflset/custom-elements-es5-adapter.js
URL mapy źródła: blaze-out/k8-opt/bin/third_party/javascript/custom_elements/fast-shim.js.sourcemap

Błąd mapy źródła: Error: request failed with status 404
URL zasobu: https://www.youtube.com/s/desktop/83093386/jsbin/webcomponents-sd.vflset/webcomponents-sd.js
URL mapy źródła: blaze-out/k8-opt/bin/third_party/javascript/polymer/v2/webcomponentsjs/webcomponents-sd.js.sourcemap

Błąd mapy źródła: Error: request failed with status 404
URL zasobu: https://www.youtube.com/s/desktop/83093386/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js
URL mapy źródła: web-animations-next-lite.min.js.map

Cookie “SOCS” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [log](https://play.google.com/log?format=json&hasfast=true&authuser=0)
Cookie “AEC” with the “SameSite” attribute value “Lax” or “Strict” was omitted because of a cross-site redirect. [log](https://play.google.com/log?format=json&hasfast=true&authuser=0)

​This?

**Comment by PANMARSAG14** [comment]
![firefox_MvMCtY7cOU](https://user-images.githubusercontent.com/81510862/178141283-998e6f16-4e18-4fd5-952b-9f3e0bb33c24.png)

**Comment by ciulinuwu** [comment]
Can you please install this version and send me the entire JSON Object? https://github.com/ciulinuwu/ciulin-s-youtube/raw/undefined-login-stuff/Ciulin's%20YouTube.user.js

**Comment by PANMARSAG14** [comment]
I don't know how to do this...

**Comment by ciulinuwu** [comment]
Dw lemme explain how!

1. Click on the Link and it'll prompt you to update the script to that version.
2. Refresh YouTube and look for the phrase compactLinkRenderer in Console
If you don't see it, make sure Debug is toggled as it outputs it to that.
3. Click on compactLinkRenderer to expand it and click through navigationEndpoint, commandMetadata and webCommandMetadata
4. Take a screenshot and send it here.

**Comment by PANMARSAG14** [comment]
![firefox_q8x3DLxRKB](https://user-images.githubusercontent.com/81510862/178141963-52a8fc72-9f76-42bd-8519-e72d8880f025.png)

**Comment by ciulinuwu** [comment]
Ah hah! Alright, I'll fix it!

**Comment by ciulinuwu** [comment]
I have uploaded a new version on the same URL. Can you please try it out and let me know if it's fixed?

**Comment by PANMARSAG14** [comment]
Unfortunately, there's only white background:
![firefox_ELQ2g3AVT8](https://user-images.githubusercontent.com/81510862/178142350-e110934a-c0e7-4a23-9983-0ef7b90b5ab1.png)

**Comment by ciulinuwu** [comment]
Oof. Anything in the console?

**Comment by PANMARSAG14** [comment]
![indeks](https://user-images.githubusercontent.com/81510862/178142454-1fc38247-b7aa-412f-9ac2-8a69c340dc2a.png)

**Comment by ciulinuwu** [comment]
Okay. Released a new version. Can you please send a screenshot of a huge block of Arrays [ [], [], [] ..] or guideSubscriptionsSectionRenderer if that shows up.

**Comment by PANMARSAG14** [comment]
![firefox_mpQHPUc9Mx](https://user-images.githubusercontent.com/81510862/178142652-f05d25fb-2166-4f76-ae92-2d433375c4fd.png)

**Comment by ciulinuwu** [comment]
Can you please click through every Number and their items and see if you can find guideEntryRenderer

**Comment by PANMARSAG14** [comment]
I found the guideEntryRenderer.

**Comment by ciulinuwu** [comment]
Okay. Can you please send a screenshot of its contents

**Comment by PANMARSAG14** [comment]
![firefox_6LQmjdXdpQ](https://user-images.githubusercontent.com/81510862/178143158-bb0d855b-4744-40d6-8a39-bf233e891f97.png)
![firefox_L7SaxIacHr](https://user-images.githubusercontent.com/81510862/178143161-bb11c820-c439-4c8d-818e-acb96c27889d.png)
![firefox_AsuT5cbRAF](https://user-images.githubusercontent.com/81510862/178143163-f0088ccf-aa20-4250-b71b-e96031956bf3.png)
![firefox_YET3Sj3LA1](https://user-images.githubusercontent.com/81510862/178143165-907b9ba2-d1be-4616-be0a-f44e973e8640.png)
![firefox_3i1o39TAZJ](https://user-images.githubusercontent.com/81510862/178143167-7c7ca62d-01f2-4b72-9749-c0d72f373459.png)
![firefox_FwKqVw8hi9](https://user-images.githubusercontent.com/81510862/178143172-b2028fcd-14ce-45f7-9b71-7d8a0466c2be.png)

**Comment by ciulinuwu** [comment]
Okay I have a suspicion. 

Can you please go to the Network tab and look for a POST request to guide?key=xxxxx and click on it and click Request and make sure it has all of these params filled? Don't send them here as these are user sensitive data, as well as the key because that's the key tied to your account!!

Params:
`{context: 
{clickTracking: {"clickTrackingParams": "Should contain random text and numbers"},
client: {
"hl": "2 letter language CODE",
"gl" "2 letter country CODE",
"remoteHost": "Your IP address",
"deviceMake": "Value doesn't matter",
"deviceModel: "Value doesn't matter",
"visitorData": "Random letters and numbers",
"userAgent": "Something like: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0,gzip(gfe)",
"clientName": "WEB",
"clientVersion": "Just version of YouTube 2.20220708.01.00 for example",
"osName": "Name of your System OS",
"osVersion": "Version of your System OS",
"originalUrl": "URL of youtube.com",
"platform": "DESKTOP",
"clientFormFactor": "Value doesn't matter",
"configInfo": {
"appInstallData": "Random letters and numbers",
"userInterfaceTheme": "What theme you're using; Light or Dark",
"timeZone": "Your Timezone",
"browserName": "Name of Browser",
"browserVersion": "Version of Browser"
}, "request": {
"useSsl": true
}, "user": {"lockedSafetyMode":false}}}`

Oh and check Headers tab, scroll to bottom Request Headers and make sure these appear:
X-Goog-AuthUser, X-Goog-Visitor-Id, X-Origin, X-Youtube-Bootstrap-Logged-In, X-Youtube-Client-Name, and X-Youtube-Client-Version. Let me know if any of them are undefined, null or empty!

**Comment by PANMARSAG14** [comment]
Okay, i checked the Headers tab, and it looks like they are normal.

**Comment by ciulinuwu** [comment]
Wait! I forgot the most important Header. Authorization!

Make sure it contains this: `SAPISIDHASH (numbers)_(random letters and numbers)`

And can you check Storage > Cookies and see if you have a cookie named SAPISID (It's used to generate the SHA-1 Hash for the Authorization header, very important!)

**Comment by PANMARSAG14** [comment]
Yup, i have the SAPISIDHASH thing.

**Comment by ciulinuwu** [comment]
Do you have the Cookie? And is the Request JSON data the same as above?

**Comment by PANMARSAG14** [comment]
Yes, i have the cookie. I don't know how to check Request JSON data.

**Comment by ciulinuwu** [comment]
![image](https://user-images.githubusercontent.com/79811506/178144568-5a1ba595-57e2-4ce8-b237-6c3ef03d82a8.png)
Network > guide?key=**** > Request. It'd be best to copy paste the JSON data into a Notepad so it's easier to go through.

**Comment by PANMARSAG14** [comment]
Okay, i copy pasted the JSON data into a Notepad.

**Comment by PANMARSAG14** [comment]
Do i have to copy the JSON data here?

**Comment by ciulinuwu** [comment]
Hi. Can you please install the latest update 0.5.24 and see if the issue still occurs?

**Comment by PANMARSAG14** [comment]
It still occurs :/

**Comment by ciulinuwu** [comment]
Hmm. I'm not sure how to fix this in the UserScript. But I think I have a solution. Can you disable the UserScript and click on your PFP and click Create Channel and see if creating a channel fixes the issues?

**Comment by PANMARSAG14** [comment]
This didn't fixed the issues.

**Comment by ciulinuwu** [comment]
Can you try 31c1dd9ae2c017d45b554735d5e480ce596e5f3a and see if it works?

**Comment by PANMARSAG14** [comment]
It works! Thank you.

**Comment by ciulinuwu** [comment]
You're welcome! Have a nice day!
