### ISSUE TITLE
is it me or youtube doesn't load when the script is on?

### ISSUE THREAD

**Issue by dylandoesgithub** [ciulinuwu/ciulin-s-youtube#30]

**Comment by ciulinuwu** [comment]
Hi. Can you please send me a screenshot of the Console logs. Thank you!

**Comment by dylandoesgithub** [comment]
<img width="1510" alt="Screen Shot 2022-07-14 at 11 18 58 PM" src="https://user-images.githubusercontent.com/109043058/179143365-083d2892-5fb1-4396-bcf0-102dec897d5e.png">
