### ISSUE TITLE
Do you plan on updating the watch bar to 2012's, or keeping it at 2010-11?

### ISSUE THREAD

**Issue by dylandoesgithub** [ciulinuwu/ciulin-s-youtube#33]
<img width="646" alt="Screen Shot 2022-07-16 at 1 06 26 PM" src="https://user-images.githubusercontent.com/109043058/179365097-4df6a1ca-88fb-441d-8265-6121aa6f3bdd.png">

this bar isn't 2012, it's 2010-11. Thanks Ciulin

**Comment by ciulinuwu** [comment]
Hi. I'm planning on updating the player to 30 Oct 2012. I'll keep this issue open to track progress!

**Comment by SirForte** [comment]
why not have both?
