### ISSUE TITLE
Video Plays Twice at the Same Time

### ISSUE THREAD

**Issue by ItsAvrilNotAveral** [ciulinuwu/ciulin-s-youtube#35]
Hi, Just a small issue.
After clicking play on a video, a few seconds afterwards a second copy of the video will start playing in the background. This only appears to occur on some videos, such as the one linked below.
https://www.youtube.com/watch?v=v49Lekz43oE

Also attached is a video of the issue.

https://user-images.githubusercontent.com/95056340/179400176-9df026be-ccbe-476a-8bc1-6b6a2e55ca44.mp4

**Comment by ciulinuwu** [comment]
Has (hopefully) been fixed in 0.5.28! Thank you for reporting the issue!
