### ISSUE TITLE
When you click on a video/enter youtube's homepage, you can see the current layout flash for just a second before it goes back to cosmic panda.

### ISSUE THREAD

**Issue by dylandoesgithub** [ciulinuwu/ciulin-s-youtube#39]
<img width="1273" alt="Screen Shot 2022-07-19 at 2 47 01 PM" src="https://user-images.githubusercontent.com/109043058/179825929-b8d8407b-906e-4189-9823-8d67fc84ba1c.png">
<img width="1112" alt="Screen Shot 2022-07-19 at 2 47 13 PM" src="https://user-images.githubusercontent.com/109043058/179825934-7c289bf2-362e-4489-b838-36d482ddb7c9.png">

**Comment by ciulinuwu** [comment]
Hi. At the moment, I can't do anything about it. I might address this in the future when I learn more about writing functional code at document-start.
