### ISSUE TITLE
will there ever be search suggestions when you type on youtube's search bar?

### ISSUE THREAD

**Issue by dylandoesgithub** [ciulinuwu/ciulin-s-youtube#40]
<img width="708" alt="Screen Shot 2022-07-19 at 2 51 24 PM" src="https://user-images.githubusercontent.com/109043058/179826766-f17538e7-842c-40b9-8986-90e2786ccd66.png">

like this but with suggestions below

**Comment by ciulinuwu** [comment]
I'll look into it after the player redesign.
