### ISSUE TITLE
Results for "Arizona Driver's Manual" not shown even though YouTube's results thing says there are 26,082 results

### ISSUE THREAD

**Issue by IoIxD** [ciulinuwu/ciulin-s-youtube#45]
![image](https://user-images.githubusercontent.com/30945097/180044419-b0528e14-4451-4d62-b2ac-8bc173cd4834.png)

What's especially weird here is what also doesn't work... "driver's manual", "arizona driver's" don't work...but "arizona", "driver's", and "manual" alone give results. [I'm also able to search for other multi word sentences, just not these ones.](https://user-images.githubusercontent.com/30945097/180044245-fe7b0e29-0434-4be8-be93-14e1410431f4.png)

**Comment by ciulinuwu** [comment]
Hi. I can't seem to replicate this issue. Also please include screenshot of the Dev Tools Console.

**Comment by IoIxD** [comment]
![image](https://user-images.githubusercontent.com/30945097/180047107-f5779fb5-c386-45ea-bc1f-59d4584c3c45.png)

**Comment by ciulinuwu** [comment]
Uhm. What OS and Browser are you using? xP

**Comment by IoIxD** [comment]
The latest Chromium on Linux x64. I'm gonna guess why you're asking and say that I have a theme that makes it look like the Classic Mac OS.

**Comment by IoIxD** [comment]
Honestly this just confirms why I knew this wouldn't work. YouTube sometimes rolls out features silently to different accounts and sometimes the features aren't even immediately obvious; I also encountered an issue with the userscript that recreated the 2015 layout, it broke for my account only due to a change (not even a new feature just. a change to the ui) that youtube rolled out.

I wish this project best of luck but sooner or later I'm probably gonna just look into making an alternative frontend or forking [Invidious](https://github.com/iv-org/invidious)

**Comment by IoIxD** [comment]
god
i'm sorry this is a vaguely related response but i went back to the new layout and my eyes actually hurt for a few seconds.
forget nostalgia i just want a layout that makes sense and isn't horribly padded and generally awful looking. i despise youtube for their inability to hire a good UX designer and then punishing those who disagree by forcing them to use the new layout anyways.
