### ISSUE TITLE
Some small issues with the video player

### ISSUE THREAD

**Issue by Herotrap** [ciulinuwu/ciulin-s-youtube#60]
Hey guys, great work overall! But I have some complaints with the player. The red, gradient is inverted, the closed captions button unaligned and the hover text too.
![Captura de pantalla 2022-08-10 a las 22 24 59](https://user-images.githubusercontent.com/53874535/184013596-c8177453-2129-4b18-acdf-92c52fc909f2.png)

**Comment by Herotrap** [comment]
A suggestion of mine is that the video should autoplay when clicked. This looks off mostly because of the new YT icon.
![Captura de pantalla 2022-08-10 a las 22 29 46](https://user-images.githubusercontent.com/53874535/184014031-8ddd40d4-7ebc-4fa1-8a80-a7924ab8ad10.png)

**Comment by ciulinuwu** [comment]
Hi. I'm currently working on redesigning the player. I'll fix these in the next update!

**Comment by Rtas-17** [comment]
I'm uncertain if there are features intentionally omitted here, but a large majority of interactions with the player, such as volume controls, context menus, seek bar and timestamp previews are also non-functional on the latest version of Firefox using Tampermonkey

**Comment by ciulinuwu** [comment]
Player will be replaced with the real 2012 HTML player. But I will need help since that is beyond my coding abilities.
