### ISSUE TITLE
undefined text when searching

### ISSUE THREAD

**Issue by Herotrap** [ciulinuwu/ciulin-s-youtube#63]
When I search, all the results have an "undefined" text before the username. IDK if it's b
![Captura de pantalla 2022-08-11 a las 21 09 07](https://user-images.githubusercontent.com/53874535/184220290-e322eefb-13c6-411f-a05d-85201dbc91ed.png)

**Comment by Herotrap** [comment]
*a bug

**Comment by ciulinuwu** [comment]
Fixed
