### ISSUE TITLE
Trailer Video playing on the background

### ISSUE THREAD

**Issue by emhlolz** [ciulinuwu/ciulin-s-youtube#66]
I really love your work! But when I'm on a channel that has a trailer video, The sound plays in the background.

System: macOS Monterey 12.4 with an M1 chip
Browser: Google Chrome Version 104.0.5112.101

Can you please fix this issue?

**Comment by ciulinuwu** [comment]
Please use the appropriate format for bug reports.

**Comment by emhlolz** [comment]
nevermind, It got fixed now
